### ISSUE TITLE
Include in readme.md

### ISSUE THREAD

**Issue by Speisaa** [lolp1/GifsSharp#1]
Hi,
could you maybe link in the readme file to my project since I´ve written a part of the Core?
Thanks :)

Link: https://github.com/Speisaa/dot-screencap

**Comment by lolp1** [comment]
Hi there,

Of course. I am actually going to re-post it under a different name since I want to do more than gifs, with proper credits both in the read-me and in the code. Sorry about that. Keep an eye out the next hour or so :)

**Comment by Speisaa** [comment]
Will do thank you for the response.
